### ISSUE TITLE
Can't create functions from fql files

### ISSUE THREAD

**Issue by rachaelmcq** [fauna-labs/serverless-fauna#10]
Creating functions from .fql files as described in the example: 
```
  functions:
    submit_order:
      name: submit_order
      body: ${file('./fql/SubmitOrder.fql')}
      role: admin
```

throws a warning and a config error:
```
 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file('./fql/SubmitOrder.fql')' could not be found.
  [...]
    Configuration error:
      [...]
       at 'fauna.functions.submit_order': should have required property 'body'
```

This is coming from an unmodified clone of the example repo, and I'm positive that that file exists at that location. It looks like maybe serverless isn't expecting the .fql extension, but I'm not sure.
