### ISSUE TITLE
Index Unique field issues

### ISSUE THREAD

**Issue by rachaelmcq** [fauna-labs/serverless-fauna#9]
Something's up with the `unique` field on indexes. The first time I tried to create an index like this: 
```
fauna:
  indexes:
    accounts_by_phone_number:
      name: accounts_by_phone_number
      unique: true
      source:
        collection: accounts
      terms:
        fields:
          - data.phone_number
      values:
        fields:
          - path: data.phone_number
```

I got an unrecognized property warning: 
```
] serverless fauna deploy
Serverless: Configuration warning:
Serverless:   at 'fauna.indexes.accounts_by_phone_number': unrecognized property 'unique'
```
But the index did create successfully, with the `unique` field set to true. The strange thing is that now, when I make changes or create new indexes with that field, I no longer get the warning. It only happened once.

Additionally, that field doesn't get picked up as a change when it's removed- i.e. create an index with `unique: true`, deploy, remove the `unique` line, and deploy again -> index still has the `unique` field set to true.
